#!/usr/bin/env python3
"""
Kernel single-source-of-truth check.

The kernels the miner actually compiles are the kSrc NSString embedded in
src/mine34_live.m (newLibraryWithSource at runtime). src/mine34_kernels.metal
is a generated reference copy: a fixed header followed by the EXACT extracted
kernel source. This tool extracts kSrc and either checks the reference for
byte equality (default) or regenerates it (--write).

Exit 0 = in sync. Exit 1 = drift (or missing reference). Any drift means the
reference was hand-edited or live.m changed without `--write`; fix by rerunning
with --write, never by hand-editing the .metal.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HEADER = (
    "// Generated file, do not hand-edit.\n"
    "// Exact kernel source compiled at runtime: extracted from the kSrc NSString in\n"
    "// src/mine34_live.m by tools/kernel_sync_check.py --write.\n"
    "// Check sync:  make kernel-sync-check     Regenerate:  make kernel-sync-write\n"
    "// Kernel documentation comments live in src/mine34_live.m next to the string.\n"
)

LINE_RE = re.compile(r'^"(.*)\\n"\s*;?\s*(?://.*)?$')


def extract_ksrc(live_path: Path) -> str:
    src = live_path.read_text()
    # Terminator is the closing  ";  of the NSString block (a quoted fragment line followed by ;).
    # The old pattern (.*?);\n stopped at the first line ending in ';'; a doc-comment line ending
    # with ';' (sip-v3 notes) truncated extraction to 3 lines and the gate passed vacuously on the
    # fragment, since the committed reference was generated by the same truncated extraction.
    m = re.search(r'static NSString \*kSrc = @\n(.*?";)\n', src, re.S)
    if not m:
        raise SystemExit(f"{live_path}: kSrc NSString block not found")
    lines = []
    for raw in m.group(1).split("\n"):
        raw = raw.strip()
        if not raw:
            continue
        lm = LINE_RE.match(raw)
        if lm is None:
            # interleaved C comment line between string fragments: doc, not source
            if raw.startswith("//"):
                continue
            raise SystemExit(f"unparsed kSrc line (update extractor): {raw[:80]}")
        lines.append(lm.group(1).replace('\\"', '"').replace("\\\\", "\\"))
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--live", type=Path, default=Path("src/mine34_live.m"))
    ap.add_argument("--metal", type=Path, default=Path("src/mine34_kernels.metal"))
    ap.add_argument("--write", action="store_true", help="regenerate the reference")
    args = ap.parse_args()

    want = HEADER + extract_ksrc(args.live)
    if args.write:
        args.metal.write_text(want)
        print(f"KERNEL_SYNC: wrote {args.metal} ({len(want)} bytes) from {args.live}")
        return 0
    if not args.metal.exists():
        print(f"KERNEL_SYNC: FAIL, {args.metal} missing (run --write)")
        return 1
    have = args.metal.read_text()
    if have == want:
        print(f"KERNEL_SYNC: PASS, {args.metal} byte-identical to embedded kSrc")
        return 0
    print(f"KERNEL_SYNC: FAIL, {args.metal} drifted from embedded kSrc in {args.live}")
    import difflib
    for line in list(difflib.unified_diff(have.splitlines(), want.splitlines(),
                                          "reference", "embedded", lineterm=""))[:40]:
        print(line)
    return 1


if __name__ == "__main__":
    sys.exit(main())
